# Change these first
owner: razvanstoica89 # Your GitHub organization or username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: RazvanStoica.dev
    url: https://razvanstoica.dev
    icon: https://razvanstoica.dev/favicon/developer.svg
  - name: AquaFilters
    url: https://aquafilters.ro
  - name: Analize Apa
    url: https://www.analizeapa.ro
  - name: Water Consulting
    url: http://water-consulting.ro
  - name: Dedurizare Apa
    url: http://dedurizareapa.ro
#  - name: Test for HEAD
#    method: HEAD
#    url: https://www.google.com
#  - name: Secret Site
#    url: $SECRET_SITE
#  - name: TCP ping
#    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.razvanstoica.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  faviconSvg: https://raw.githubusercontent.com/razvanstoica89/upptime/master/assets/icon.svg
  logoUrl: https://raw.githubusercontent.com/razvanstoica89/upptime/master/assets/icon.svg
  name: Razvan Stoica Status
  introTitle: "**Razvan Stoica** Systems Status"
  introMessage: "This is a status page which uses **real-time** data from my [GitHub repository](https://github.com/razvanstoica89/upptime)."
  navbar:
    - title: Razvan Stoica Home
      href: https://razvanstoica.dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
